"""add bairro to denuncia

Revision ID: 371c958c6539
Revises: f2a8f606da17
Create Date: 2025-06-22 10:53:36.621156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371c958c6539'
down_revision = 'f2a8f606da17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.drop_column('bairro')

    # ### end Alembic commands ###
