"""add data_encerramento to denuncia

Revision ID: f2a8f606da17
Revises: 28403d083e24
Create Date: 2025-06-21 22:51:37.631884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a8f606da17'
down_revision = '28403d083e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_encerramento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.drop_column('data_encerramento')

    # ### end Alembic commands ###
